---
apiVersion: v1
kind: Secret
metadata:
 name: tjwa-blue-params
stringData:
 values.yaml: |
   ---
   workload_name: tjwa-blue
   replicas: 1
   hostname: tjwa-blue.snative.dev
   cluster_issuer: gcp-clouddns