---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
 name: tjwa-blue
spec:
 serviceAccountName: default # ServiceAccount on run cluster with permissions to deploy Package, see "Set up run Cluster Namespaces"
 packageRef:
   refName: tjwa.default.tap # name of the Package
   versionSelection:
     constraints: 20231008025417.0.0+build.f39caaf # version of the Package
 values:
 - secretRef:
     name: tjwa-blue-params # Secret created in previous step