---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
 name: tjwa-green
spec:
 serviceAccountName: default # ServiceAccount on run cluster with permissions to deploy Package, see "Set up run Cluster Namespaces"
 packageRef:
   refName: tjwa.default.tap # name of the Package
   versionSelection:
     constraints: ">=0.0.0" # version of the Package
 values:
 - secretRef:
     name: tjwa-green-params # Secret created in previous step