apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: tjwa
  namespace: default
spec:
  virtualhost:
    fqdn: tjwa.snative.dev
    tls:
      secretName: tjwa-route-cert
  routes:
  - conditions:
    - prefix: /
    services:
    - name: tjwa
      port: 8080
      weight: 50
    - name: tjwa-blue
      port: 8080
      weight: 50

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tjwa-route-cert
  namespace: default
spec:
  dnsNames:
    - tjwa.snative.dev
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: gcp-clouddns
  secretName: tjwa-route-cert
  usages:
    - digital signature
    - key encipherment